language: node_js
node_js:
- '8'
script: yarn test:coverage
after_success: yarn run coveralls
deploy:
  provider: npm
  skip_cleanup: true
  api_key:
    secure: RWl7Jtqhge40LfZbpOjDtXGvHpgeY1s7NZ3nDUOQxvDgSUOBgMQ3Pmir6fA1GmAtYmDgZ27QrlfK+I0vZqROw1Nsr2bG/JzFL8yZuMAxCaaw+WWE8Z14s4nUnteddYHD1ZMtUkEj8efHfpJQBv+PaIOu+1mWPIFVZsmvicgpp/ucSV5vJz5z2c4CXj5SRkwOlvH7j8ayDQR3/WMMmkJ2e1XVZnKd/YDrQaaU8elJ/oth34RihAJM4h2IWmMDl1MiFMVEz46FyMtws5VVDxpscfbeZ/w10a4WCKbFMb/lf7prH1QBMnXGLJC8Vb4eXxec9bGAh0KxTjJIzVxpsokg8LsSrlG6EfC+zuRG8UAZgo4nWwAb6kAdJkZh6+jiU9K6Gne9hKvUkNj60YkuK3mBHL/2a2FyIX8ehl/SIpNmH5nJRdHg5CJ/7pFHRVGGn0GPNmnLsvo4L9NUyJ9aAVzc0Lm876RICEMVAZYnLivDguHOrRiLVNXGgAB6KMr0ijCU+SuCYTSHpTGJZlYbfWectnbbFd5gSPwiqiHvCQBYGb2WU61Zn+gOMZImVxGTBZHHjBV7W3EkAc2ZZW63YDHGFit6UqUPiR7bOZNN7Jn0ZY6johIAx5MFYPOBzx5sMvewlQFxg7tMxSIlhAOlpEommp7ncrgapQiQQ6BbayJG5wI=
  on:
    tags: true
  email:
    secure: iCwRsRF/aQXGQxO+mLKfafHFd4SxUJQ/EZuTd/ndg/2imF69gp4OFq7vzZVQ8CC4QKP8SjIkP9mTtk7Ergwordo7kV6S4vpv7/f4QfCUUJUt/CIn7lSUTAURN2qK0eWu84IyHmKGq1BlCFKJKI//bfcFKZuyhihEG6yPz1N43tAYLK6YTn0ws3mLiRZ4/Wtmg1nHIKf9/K4ByyKQLq1MeX7qbww+o9TKHHPUIPpYLNCG6xjcsWV8wqYytoUpsWiM//vYPF8mO8IiaAbyMVGQxxgK8mrqizXxy4zQmm5TrZE78wZZ7TXl9y9A+sWow5WSwV2EhUOt6yPXK/nCZCI2ukuvuAfqCuHqry1HvPAmwcPXEJKM48WxcFkx+YJo/PGToBnpT8X35t7uVpJM62RfsvpCccnkkpDSjDY5OhuPDqUqG69Pdl0/dCMxpOrnEyvAWrcpWU/ZpJbjIgigdysMq5EvawjZ+DBUQZoTY+Eq9Qt+pV2lZNgkPrcAt9cjvJVrN2xBYq268Z6c2eu5LjwQhyz5vHIE77CrSHTu2me+H+X5Q2KE316oAY2Bzj/6oAadsnRuhgp2qeY7ofSG/Ak/gvpHYMoB2Qzc4WGZ7TYfPjbZVvFjJtpD2iP1uHOe+VxNTtTjOYa712J2NaThXI6mDR7pmgpNPc8ZXP32iYG3WpU=
